### PR TITLE
Fix test.sh not reporting py.test result code and ganache-cli process not killed

### LINKED ISSUE #100: False positive Travis CI builds due to test.sh not reporting py.test result code
## Environments
Travis CI

## Current Behavior
Test passed (ex. most recent master build [#1019](https://travis-ci.org/makerdao/pymaker/builds/534946661))

## Expected Behavior
Test should fail since the underlying py.test failed ([raw logs](https://api.travis-ci.org/v3/job/534946662/log.txt))

## Failure Information
It seems in `test.sh`, the py.test exit code was hidden by the follow up commands. I've made a quick fix and will post a pull request to follow up.

## Extended Issues
Unfortunately this also means the unit-tests have been failing and there is an issue with ganache-cli when testing dss. That probably should be in its own separate issue.

### PR DESCRIPTION
**Pull request by Detoo**
## Target Issues
fixes #100

## Descriptions
- Propagate py.test exit code so Travis CI can catch it
- In addition, `killall` didn't seem to pattern-match the process properly on Mac OS so I've made a few changes to fix it

## Proof-of-work (or more accurately: not-work)
https://travis-ci.com/Detoo/keeper/builds/118022194 (the test failed as expected)

### CODE REVIEW

File: test.sh [hunk 1]
```diff
@@ -1,8 +1,12 @@
 #!/bin/sh
 
 ./ganache.sh &>/dev/null &
+GANACHE_PID=$!
```
Comment (EdNoepel) [inline test.sh]: I tried this too.  $! returns the PID of the ganache.sh script, not the node process actually running ganache.

**Comment by EdNoepel** [comment]
I believe I fixed the issue killing ganache in https://github.com/makerdao/pymaker/pull/99.  I haven't tested on MacOS.

File: test.sh [hunk 2]
```diff
@@ -1,8 +1,12 @@
...
 sleep 5
 
 py.test --cov=pymaker --cov-report=term --cov-append tests/
+TEST_RESULT=$?
```
Comment (EdNoepel) [inline test.sh]: We do need this bit; thank you.

**Comment by EdNoepel** [comment]
Much thanks!

File: test.sh (hunk 1 above)
Comment (Detoo) [reply test.sh]: `pkill -P $GANACHE_PID` below will take care of it. What it does is it finds the child PID (the node process) and kills it. It works on my mac but also I expect `pkill` to behave similarly on other Linux shells.

File: test.sh (hunk 2 above)
Comment (Detoo) [reply test.sh]: glad to help :) Thanks for the works!
